### PR TITLE
Event source preview

### PR DESCRIPTION
**Pull request by acmmlu**
I don't want to merge this, just looking for feed back on the structure of this, things like:
Do these attributes make sense? My thinking is you add an EventAttribute that says what kind of event to make based on the status code.
In theory you could have n different event types fire on status 200 for example (although that's not how it's written now, would need a small change in EventSourceMiddleware).
The downside is that while adding these attributes you have to know every status code that can be produced by that endpoint.
I'm thinking of adding a default implicit 500 one for if an endpoint doesn't supply one.
I also have concerns like not being able to leverage the model binder and possibly running into situations where while building the event you have to redo work that was done when the endpoint was hit.
The scenario I'm most concerned about is one where you can't determine how to populate the event by status code + request body + response body alone

### CODE REVIEW

**Comment by Jeremy-Barnes** [comment]
All the string magic here is very gross. Deserializing the request and response in the Event and just hoping that we have the right type is rough. This is most dangerous if the request/response type changes - there's no way to tie those together until you run the API and it explodes. The more different response codes we have, the worse it gets.

We can shrink the blast radius of that a bit, potentially, by passing in the request/response types as Attribute parameters. It doesn't buy us any compile-time safety, but it puts all the moving pieces in one place. That does throw us into a generics/Object hellhole for actual construction though.

**Comment by Jeremy-Barnes** [comment]
> Do these attributes make sense? My thinking is you add an EventAttribute that says what kind of event to make based on the status code.

Yes, I think these are perfectly clear


> The downside is that while adding these attributes you have to know every status code that can be produced by that endpoint.

This doesn't trouble me too much, having that in the Controller is kind of nice, honestly.

> I also have concerns like not being able to leverage the model binder and possibly running into situations where while building the event you have to redo work that was done when the endpoint was hit.

This is related to my other comment too.

> The scenario I'm most concerned about is one where you can't determine how to populate the event by status code + request body + response body alone

I think this is a likely situation, we discussed this a bit at 1D - its okay, but does mean that we need a non-middleware way of publishing these events. I'm beginning to think that is cleaner anyways, but not 100% against this approach. Want it to work very badly.

**Comment by Jeremy-Barnes** [comment]
Tagging @maybejosh to see if he has thoughts on getting this to be less string-magical.

Context: https://github.com/Jeremy-Barnes/Critters.NET/discussions/50

**Comment by acmmlu** [comment]
To your last point, publishing events without or alongside this middleware stuff should be easy, just verbose. Again this is really making me yearn for python style decorators. I'll see if I can avoid any of the string magic ugliness without making it even more ugly.

Also I'm thinking we're gonna need the route component to do anything useful for a lot of these endpoints like SubmitGameScore. Again, super easy with string magic (context.GetRouteData()), but blows up spectacularly if your route changes. This one actually seems like it's intended to work via string magic so I'm not sure how to make that any cleaner.

**Comment by acmmlu** [comment]
Would this be more tolerable with a unit test that looks at all the endpoints and their corresponding events and makes sure the event is up to date with what the endpoint looks like?

**Comment by Jeremy-Barnes** [comment]
What up nerd

**Comment by Jeremy-Barnes** [comment]
Hello world

**Pull request closed without merging**
